### ISSUE TITLE
"No freebies currently / No new notifications! Skipping" permanently 

### ISSUE THREAD

**Issue by bullik01** [azhuge233/IndiegalaFreebieNotifier#2]
Hi! I get "No freebies currently / No new notifications! Skipping" permanently and don't get any notifications.
And thats all :(
![image](https://github.com/azhuge233/IndiegalaFreebieNotifier/assets/4389593/13ceb096-5c1b-4472-881a-5414e0c4e667)

But at that moment indiegala have few freebies

**Comment by azhuge233** [comment]
Seems like playwright isn't able to fetch [freebies.indiegala.com](https://freebies.indiegala.com).

- Try to increase `TimeOutMilliSecond` in config.json.
  - Let browser wait longer to avoid network issue.
- Set `EnableHeadless` to `false` to see browser's progression.
  - Does the browser open correctly? (linux compatability issue)
  - Does the browser load page? (network issue)
  - Does the browser get blocked by Indiegala? (IP, scraping stradegy issue)
- Check log files under log directory for more debug output.

Indiegala also has anti-scraping stradegy, it's better to tune down the scraping frequency.

I only have Debian 12 VMs right now so I can't test this on Linux (Playwright only supports Debian 11, Ubuntu 20.04 and Ubuntu 22.04), below is a standard output on WIndows Server 2022.
![Snipaste_2023-08-09_08-09-21](https://github.com/azhuge233/IndiegalaFreebieNotifier/assets/17763056/5983f572-169f-41f7-a62d-b8802dfc134a)

**Comment by azhuge233** [comment]
Hi, just tested on a Debian 11 VM, no compatibility issue. Maybe you should check your network/scraping strategy.
![Snipaste_2023-08-09_16-30-46](https://github.com/azhuge233/IndiegalaFreebieNotifier/assets/17763056/654bb476-f42e-4bca-8f1f-81d412a10966)
