### ISSUE TITLE
"No freebies currently / No new notifications! Skipping" permanently (Continuation)

### ISSUE THREAD

**Issue by bullik01** [azhuge233/IndiegalaFreebieNotifier#3]
Sorry for creating a new issue, but the previous one was closed and I didn't have time to reply there. I'll answer in more detail here.

**Comment by bullik01** [comment]
![image](https://github.com/azhuge233/IndiegalaFreebieNotifier/assets/4389593/307dc17f-7843-417d-b553-4b8b4f94a03c)

Log:
![image](https://github.com/azhuge233/IndiegalaFreebieNotifier/assets/4389593/fb79262f-de07-4d8d-8975-a668bbaeff21)

Config:
![image](https://github.com/azhuge233/IndiegalaFreebieNotifier/assets/4389593/e7e18576-96f8-45c4-bd11-b3fdb19f71ca)

I don't have any connection issues (home 1 gbit/s internet, indiegala in browser (Chrome Latest) works perfectly.

Playwraith need GUI (DE+WM) for work? Or it can be launched on terminal-only system too?

**Comment by bullik01** [comment]
I found problem. User just need latest dotnet :)

Thanks for your amazing projects!

**Comment by bullik01** [comment]
I found problem. User just need latest dotnet :)

Thanks for your amazing projects!

**Comment by azhuge233** [comment]
Gald to hear you solved this!
Thank you for your support.
